FROM python:3.12-slim

WORKDIR /TE_back

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./python/my_work /TE_back

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]